
runtest:
	@if [ -x run.sh ] ; \
	then \
		(./run.sh);\
	else \
		(echo "Error: no run.sh file") \
	fi

#	ls
#	./aflat "test.act" > "test2.prs"
#    ./prsim "test2.prs"
#    source "test2.prsim"
#    echo "test 2 complete"
