/*************************************************************************
 *
 *  Copyright (c) 2023 Rajit Manohar
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor,
 *  Boston, MA  02110-1301, USA.
 *
 **************************************************************************
 */
#include "synth.h"
#include <common/config.h>
#include <common/misc.h>
#include <act/passes.h>


/*
  To synthesize a design, we need to do a few things:

  - all data types must be implemented with bools
    => structures must be implemented 
    => int and bools must be implemented
    => channels must be implemented
  
  - the implementation must override already defined variables
  - the implementation must intantiate any fresh variables


  Convention:

     prefix_<name> is used to implement <name>, where <name> is the
     *expanded* version of the original type.

     The implementation begins by importing the original file.

     
*/

ActSynthesize::ActSynthesize (const char *prefix,
			      char *infile,
			      char *outfile,
			      char *exprfile)
{
  const char *expr_file;
  
  if (outfile) {
    _out = fopen (outfile, "w");
    if (!_out) {
      fatal_error ("Could not open file `%s' for writing", outfile);
    }
  }
  else {
    _out = stdout;
  }

  if (config_exists ("act.output_window")) {
    _pp = pp_init (_out, config_get_int ("act.output_window"));
  }
  else {
    _pp = pp_init (_out, 78);
  }

  expr_file = exprfile;
  if (expr_file) {
    _expr = fopen (expr_file, "w");
    _ename = Strdup (expr_file);
    if (!_expr) {
      fatal_error ("Could not open file `%s' for writing", expr_file);
    }
  }
  else {
    _expr = NULL;
    _ename = NULL;
  }

  pp_printf_raw (_pp, "/* auto-generated by logic synthesis */\n");
  if (infile) {
    pp_printf_raw (_pp, "import \"%s\";\n", infile);
  }
  pp_forced (_pp, 0);

  _top = NULL;
  _decomp_vx = NULL;
  _new_ports = NULL;
  _prefix = prefix;
  _errmsg = NULL;
  _echp = NULL;
}


void ActSynthesize::Close ()
{
  if (_pp) {
    pp_stop (_pp);
    _pp = NULL;
  }
  if (_out) {
    if (_out != stdout) {
      fclose (_out);
      _out = NULL;
    }
  }
  if (_expr) {
    fclose (_expr);
    _expr = NULL;
  }
  if (_ename) {
    FREE (_ename);
    _ename = NULL;
  }
  if (_errmsg) {
    FREE (_errmsg);
    _errmsg = NULL;
  }
}

ActSynthesize::~ActSynthesize ()
{
  Close ();
}


bool ActSynthesize::prepSynthesis (ActPass *ap, bool run_arb)
{
  Process *p = ap->getRoot ();
  
  if (!p) {
    return false;
  }

  if (!p->isExpanded()) {
    if (!ActNamespace::Global()->isExpanded()) {
      ActNamespace::Act()->Expand ();
    }
    p = p->Expand (ActNamespace::Global(), p->CurScope (), 0, NULL);
  }
  _top = p;


  /*-- Apply standard decompositions --*/

  ActPass *gp;
  ActCHPFuncInline *ip;
  ActCHPMemory *mem;
  ActCHPArbiter *arbp;

  gp = ActNamespace::Act()->pass_find ("finline");
  if (gp) {
    ip = dynamic_cast<ActCHPFuncInline *> (gp);
  }
  else {
    ip = new ActCHPFuncInline (ActNamespace::Act());
  }
  Assert (ip, "error in inline pass");
  if (!ip->completed()) {
    ip->run (p);
  }

  gp = ActNamespace::Act()->pass_find ("chpmem");
  if (gp) {
    mem = dynamic_cast<ActCHPMemory *> (gp);
  }
  else {
    mem = new ActCHPMemory (ActNamespace::Act());
  }
  Assert (mem, "error in mem pass");
  if (!mem->completed()) {
    mem->run (p);
  }

  gp = ActNamespace::Act()->pass_find ("chparb");
  if (gp) {
    arbp = dynamic_cast<ActCHPArbiter *> (gp);
  }
  else {
    arbp = new ActCHPArbiter (ActNamespace::Act());
  }
  Assert (arbp, "error in arbiter pass");
  if (!arbp->completed() && run_arb) {
    arbp->run (p);
  }

  /*-- Emit any additional imports needed --*/
  emitTopImports (ap);

  return true;
}


void ActSynthesize::finalSynthesis (Process *p)
{
  if (!p) {
    return;
  }
  emitFinal ();
}


bool ActSynthesize::checkSynth (ActPass *ap, Process *p)
{
  if (p->getlang() && p->getlang()->getchp()) {
    struct pHashtable *H;
    bool ret;
    H = phash_new (4);
    ret = _check (H, p->CurScope(), p->getlang()->getchp()->c);
    phash_free (H);
    return ret;
  }
  else {
    return true;
  }
}

bool ActSynthesize::_check (struct pHashtable *H, Scope *sc, act_chp_lang_t *c)
{
  listitem_t *li;
  act_chp_gc_t *gc;
  act_connection *conn;
  phash_bucket_t *b;
  static int nest = 0;

  if (!c) return true;

  nest++; // used to filter top-level concurrency

  if (!customCheck (c)) {
    return false;
  }

  switch (c->type) {
  case ACT_CHP_COMMA:
    if (nest == 1) {
      // outer parallel
      for (li = list_first (c->u.semi_comma.cmd); li; li = list_next (li)) {
	act_chp_lang_t *ch = (act_chp_lang_t *) list_value (li);
	phash_clear (H);
	if (!_check (H, sc, ch)) {
	  nest--;
	  return false;
	}
      }
      return true;
    }
    // fall-through: standard check
  case ACT_CHP_SEMI:
    for (li = list_first (c->u.semi_comma.cmd); li; li = list_next (li)) {
      act_chp_lang_t *ch = (act_chp_lang_t *) list_value (li);
      if (!_check (H, sc, ch)) {
	nest--;
	return false;
      }
    }
    break;

  case ACT_CHP_ASSIGN:
  case ACT_CHP_SKIP:
    break;

  case ACT_CHP_SELECT:
  case ACT_CHP_SELECT_NONDET:
  case ACT_CHP_LOOP:
  case ACT_CHP_DOLOOP:
    for (gc = c->u.gc; gc; gc = gc->next) {
      Assert (!gc->id, "Guard loops still present during synthesis check!");
      if (gc->s) {
	if (!_check (H, sc, gc->s)) {
	  nest--;
	  return false;
	}
      }
    }
    break;

  case ACT_CHP_SEND:
  case ACT_CHP_RECV:
    if (c->u.comm.var && c->u.comm.e) {
      std::string emsg;
      emsg = "Exchange channels are currently not synthesizable.";
      _echp = c;
      _errmsg = Strdup (emsg.c_str());
      return false;
    }
    if (c->u.comm.flavor != 0) {
      std::string emsg;
      emsg = "Split communication channels are not synthesizable\n\tvia the automated flow.";
      _echp = c;
      _errmsg = Strdup (emsg.c_str());
      return false;
    }
    conn = c->u.comm.chan->Canonical (sc);
    Assert (conn, "Hmm");
    b = phash_lookup (H, conn);
    if (!b) {
      b = phash_add (H, conn);
      b->i = 0;
    }
    if (c->type == ACT_CHP_SEND) {
      if (b->i == 0 || b->i == 1) {
	b->i = 1;
      }
      else {
	std::string emsg;
	emsg = "Internal self-synchronization is not supported\n\tvia the automated synthesis flow.";
	_echp = c;
	_errmsg = Strdup (emsg.c_str());
	return false;
      }
    }
    else {
      if (b->i == 0 || b->i == 2) {
	b->i = 2;
      }
      else {
	std::string emsg;
	emsg = "Internal self-synchronization is not supported\n\tvia the automated synthesis flow.";
	_echp = c;
	_errmsg = Strdup (emsg.c_str());
	return false;
      }
    }
    break;

  case ACT_CHP_SEMILOOP:
  case ACT_CHP_COMMALOOP:
  case ACT_CHP_HOLE:
  case ACT_CHP_ASSIGNSELF:
  case ACT_CHP_MACRO:
  case ACT_HSE_FRAGMENTS:
    fatal_error("Unexpected CHP type (%d); should have been filtered out.\n", c->type);
    break;

  case ACT_CHP_FUNC:
    // filtered and replaced with skip for synthesis
    break;

  default:
    fatal_error ("Unknown CHP type (%d)\n", c->type);
    break;
  }
  nest--;
  return true;
}


void ActSynthesize::printSynthError (FILE *fp)
{
  if (!_errmsg) {
    fprintf (fp, "no error!");
    return;
  }
  fprintf (fp, "%s\n", _errmsg);
  if (_echp) {
    fprintf (fp, "  CHP statement: ");
    chp_print (fp, _echp);
  }
}


int ActSynthesize::shouldSynthesize (Process *p)
{
  ExternMacro *macro = new ExternMacro (p);

  if (macro->isValid()) {
    /*-- we already have an external definition --*/
    delete macro;
    return NO_SYNTHESIS;
  }
  delete macro;

  if (!p->getlang()) {
    // no languages, just a dummy process or instances
    return TRIVIAL_SYNTHESIS;
  }

  // if there are production rules, we are done with synthesis already
  if (p->getlang()->getprs()) {
    return TRIVIAL_SYNTHESIS;
  }

  if ((p->getlang()->getchp() && allowCHP() ||
       (p->getlang()->getdflow() && allowDFLOW()) ||
       (p->getlang()->gethse() && allowHSE()))) {
    // we have work to do
  }
  else {
    return TRIVIAL_SYNTHESIS;
  }

  if (p->getns() && p->getns() != ActNamespace::Global()) {
    if (strcmp (p->getns()->getName(), "std") == 0) {
      list_t *l = ActNamespace::Act()->getDecompTypes ();
      if (l) {
	for (listitem_t *li = list_first (l); li; li = list_next (li)) {
	  Process *tmp = (Process *) list_value (li);
	  if ((tmp->isExpanded()) && p == tmp ||
	      (tmp == dynamic_cast<Process *>(p->getUnexpanded()))) {
	    list_free (l);
	    return NO_SYNTHESIS;
	  }
	}
	list_free (l);
      }
    }
    else {
      ActNamespace *ns = p->getns();
      while (ns->Parent() != ActNamespace::Global()) {
	ns = ns->Parent ();
      }
      if (strcmp (ns->getName(), "syn") == 0) {
	/* check for built-in synthesis */
	const char *nm = p->getUnexpanded()->getName();
	int len = strlen (nm);
	if (len > 9 && (strcmp (nm + len - 8, "_builtin") == 0)) {
	  // dummy!
	  return DUMMY_SYNTHESIS;
	}
      }
    }
  }
  return ACTUAL_SYNTHESIS;
}

